### ISSUE TITLE
latest osu! stable update broke osu! database loading

### ISSUE THREAD

**Issue by flameboi900** [Piotrekol/StreamCompanion#109]
https://imgur.com/a/oBR2uEr

**Comment by CapnS** [comment]
While this is a very bad way to report an issue, it is nonetheless still an issue because I am running into the same error. Once I updated it, this error message popped up, and I've gone as far as to completely delete and reinstall StreamCompanion, but to no avail. After this error message pops up, if you try to exit StreamCompanion using the provided Exit button or the default exit button, it stops responding and you have to force close it with Task Manager.

**Comment by Piotrekol** [comment]
just to be clear: newest __osu!__ update broke it, not changes in SC code. fix coming.

**Comment by Eroo36** [comment]
I am still having the same problem after your latest fix for it
https://puu.sh/EBNFe/47b75cb3f4.png
