### ISSUE TITLE
Displays Incorrect DiffName

### ISSUE THREAD

**Issue by YKilin** [Piotrekol/StreamCompanion#11]
I have the same problem as #6. Memory scanning is enabled, but it seems that SC just display a default DiffName.
And the DiffName won't update if I select another difficulty.
Is it really impossible to determine the cause of this situation?

System: Windows 10 1709
I uses the configuration file to define the Song Directory, it is not the default location.
I'm not sure whether this is related to this problem.

![](https://user-images.githubusercontent.com/24877906/35777334-1e4a79de-09e7-11e8-837e-dcc9bd605dc3.png)

![](https://user-images.githubusercontent.com/24877906/35777337-2888ef84-09e7-11e8-80e8-057b25d4de7b.png)

**Comment by Piotrekol** [comment]
#6 is unrelated to this issue.
SC was never able to distinguish map difficulties in song select.
This at the time of creating SC was intended, due to limitations of what osu! is providing via MSN and frequency of this data(it only sends MSN requests on map changes, not difficulty changes) 

However you might see this added(per diff recognition) really soon.

**Comment by YKilin** [comment]
Oh really. It will be a correct DiffName after I start playing.
Because I met the same problem as #6 in the previous version (really), I thought this problem might not be fixed.
Sorry to disturb you.

**Comment by Piotrekol** [comment]
Unless I find something totally breaking this should be released tomorrow
https://streamable.com/hub9a

**Comment by YKilin** [comment]
Nice!
