### ISSUE TITLE
osu.db read fails on v191107.16

### ISSUE THREAD

**Issue by uwuplant** [Piotrekol/StreamCompanion#112]
w10 64bit, works fine on v191103.18
latest osu! stable release
if any other info's needed, then ask c:

**Comment by Piotrekol** [comment]
are you playing on bancho c: ?
can't reproduce on neither osu! stable or cutting edge.

**Comment by maxwellx** [comment]
Its working in osu! beta version

**Comment by uwuplant** [comment]
Yes I am. I'm on w10 ltsc though. Would that make a difference?

**Comment by Piotrekol** [comment]
Shouldn't... Can you check what version of CollectionManager.dll is located in your SC install folder? https://i.imgur.com/ezX29Gw.png.
If it's not 1.0.4, either SC isn't updated or updater failed to replace some of the files(because of antivirus? manually edited folder perms?). In that case, I'd recommend reinstalling SC.

**Comment by uwuplant** [comment]
In school atm, will do in a few hours

**Comment by sa-shiro** [comment]
Same issue, even after completly removing streamlabs im still getting the error that the loading of osu!.db failed

**Comment by Piotrekol** [comment]
streamlabs doesn't provide any easy way of allowing custom plugins - so there is no way of reading live patterns in it.

**Comment by sa-shiro** [comment]
oh well ok thanks, then ill stick to obs

**Comment by uwuplant** [comment]
nvm, it's magically working again haha
