### ISSUE TITLE
osu!.db  FAILED

### ISSUE THREAD

**Issue by Aitorico** [Piotrekol/StreamCompanion#116]
https://gyazo.com/20c501f71f699dcbd524879ef2240d9e
So this is my issue and I dont know how to solve it, I tried with some other pp counters and them worked pretty good, but they are not using this thing named "osu!,db" and the other pp counters arent that accurate so, please help me.

**Comment by Piotrekol** [comment]
Found report on sentry and it seems that for one reason or another [your SC is using outdated CollectionManager version](https://user-images.githubusercontent.com/4990365/69656766-70561b80-1079-11ea-872a-8d24eed6482e.png) - 1.0.3 instead of 1.0.4(with handles "osu!.db").
Have you tried reinstalling StreamCompanion?

**Comment by Aitorico** [comment]
Okay, that actually helped me a lot, thanks, love ya.
