### ISSUE TITLE
osuOverlayPlugin.dll could not be loaded.

### ISSUE THREAD

**Issue by Saryuii** [Piotrekol/StreamCompanion#122]
Ever since I have downloaded the application it kept on saying osuOverlayPlugin.dll could not be loaded. I deleted the file (osuOverlayPlugin.dll) but my visualizer would calibrate for my pp, 100s, the 50s, and misses. I also don't know what to put osuOverlayPlugin.dll in which file. May I have some help?

**Comment by Piotrekol** [comment]
Couldn't be loaded because of what? There is error provided with these messages.
But most likely all you have to do is to use in-game overlay setup that's available on latest release page, instead of trying to copy it manually from zip file
https://github.com/Piotrekol/StreamCompanion/releases/tag/v191115.18
`StreamCompanion.-.ingameOverlay.Setup.exe`

I'll most likely remove in-game overlay zip file download from future releases, as it just creates more confusion for no reason.
