### ISSUE TITLE
np stops working during "Playing" after watching replay

### ISSUE THREAD

**Issue by ceilingwaffle** [Piotrekol/StreamCompanion#14]
After watching a replay, and then playing any map, the "Now Playing" info displays _!ArtistRoman! - !TitleRoman! [!DiffName!]_

A relaunch of osu SC is required to fix it. SC displays the artist/song name correctly when "listening" to a map, but as soon as you start "playing" the map, it changes to _!ArtistRoman! - !TitleRoman! [!DiffName!]_

SC version: 180220.20
Screenshot of Map Formatting settings: https://i.imgur.com/Un7rL1c.png

**Comment by Piotrekol** [comment]
Um yeah, I might have been unclear in what "memory pattern" does.
You don't need "memory pattern" set on `np_all` at all, this will fix your issue.


Release with clears this up and fixes these patterns saving when not playing(not intended) should come later today.
I'll just copy fragment of my answer on osu forums:

---------
> To be able to use these(and only these) you need pattern set to be a memory https://i.imgur.com/2TaQmIF.jpg

>**(and only these)**

You can still use all patterns in obs plugin without setting every single one as a memory one.
https://i.imgur.com/Q7GpX7C.jpg

Also these memory patterns outputting when not playing is a bug, with will be fixed in next release(will be empty when not playing)

**Comment by ceilingwaffle** [comment]
Understood, thanks 👍
