### ISSUE TITLE
[Enhancement] Various QoL Requests for In-Game Overlay / In general

### ISSUE THREAD

**Issue by Yuwuyuwukowo** [Piotrekol/StreamCompanion#191]
- Text shadow
- Text border + color
- Text background fill + background border + color for both + rounded / squared background border
- Universal token / other method for just putting normal strings in the in-game overlay without having to waste some random token for text
- Allow "%" to display properly (not sure if personal issue), because without it you can't do "100%: 324pp", it just shows "100: 324pp" for example
- Different "Listen" for multiplayer, since where you put your pp info will probably not look good in multi as it does in song select

![image](https://user-images.githubusercontent.com/66982744/92320664-cda7d180-efe8-11ea-9c58-b9392ee4c447.png)
![image](https://user-images.githubusercontent.com/66982744/92320696-f9c35280-efe8-11ea-96da-f7f124854336.png)

**Comment by Piotrekol** [comment]
`Universal token / other method for just putting normal strings in the in-game overlay without having to waste some random token for text`
Not sure what you mean. Text that is shown in overlay comes from Output patterns, with can contain any text ( they don't even have to use any token)

`Allow "%" to display properly (not sure if personal issue), because without it you can't do "100%: 324pp", it just shows "100: 324pp" for example`
entering `%%` instead of `%` seems to work.

`Different "Listen" for multiplayer, since where you put your pp info will probably not look good in multi as it does in song select`
Sure, that seems like a valid use case. SC is already able to detect different "listen states"(but only one is shown to user). What would we expect to see here? SC could even output different "listening" event depending on the screen osu is currently in (multiplayer room selection, inside mp room, mp resultsScreen.. I think that's all of them)

as for 3 proposed ingameOverlay changes - no promises or ETAs

**Comment by Piotrekol** [comment]
Won't be finishing this one - while in-game overlay will still exist, it's now mostly superseded by https://github.com/Piotrekol/StreamCompanion/pull/263
Everything mentioned here is easily possible with this solution.
