### ISSUE TITLE
EZ and HT mods preview and live showing wrong PP

### ISSUE THREAD

**Issue by 96fleur** [Piotrekol/StreamCompanion#195]
When selecting EZ and/or HT mods the pp only refresh when you click on the mod, you have to go through the whole mod selection and pick it again to make it count. Otherwise it showing wrong pp all map long. ( v200813.17 )

**Comment by Piotrekol** [comment]
Can't reproduce. Provide exact reproduce steps or record a video showing the problem if possible.

**Comment by 96fleur** [comment]
Hello, check this video ( https://www.youtube.com/watch?v=KxkDtTBmevg )
timestamp 3:09
Regards.

Le jeu. 17 sept. 2020 à 19:21, Piotr Partyka <notifications@github.com> a
écrit :

**Comment by Piotrekol** [comment]
I can only guess, but I think reproduced your issue by holding quick retry button for a straight minute or so
![image](https://user-images.githubusercontent.com/4990365/93661882-c1495d00-fa5b-11ea-9662-a81a4c339f69.png)
currently, whenever this happens SC just bails and uses NoMod as your mods for this play(event).
I'll add retry mechanism here since there's no other way to handle this as memory reads can fail at random(especially when starting a play)
