### ISSUE TITLE
Frequent "Beatmap could not be loaded" errors with memory pooling enabled.

### ISSUE THREAD

**Issue by Tj7223** [Piotrekol/StreamCompanion#22]
As the title says, when memory pooling is enabled, the game frequently gives a "Beatmap could not be loaded" error, and also often forces you to do a full refresh (default F5) in game to be able to see and play the map. It seems to happen on both Stable and Beta. I don't know what else to put here, so feel free to ask questions about my game or anything else.

**Comment by Piotrekol** [comment]
This is exactly what [this line](https://github.com/Piotrekol/StreamCompanion/blob/master/osu!StreamCompanion/Code/Modules/MapDataReplacements/PP/PpReplacements.cs#L59) is trying to prevent, and I haven't been able to reproduce this myself ever since. 

I'll most likely end up adding a setting option to allow for increasing this delay until a better solution can be found.

For those interested: I already tried opening osu files with "shared" lock, but osu! seems to want to have exclusive access to these files, that's why there's that not-so-great solution.
