### ISSUE TITLE
Names not display correctly sometimes for maps after import to osu

### ISSUE THREAD

**Issue by Stekeblad** [Piotrekol/StreamCompanion#3]
OSU! version: b20160821.1 (stable)
Osu!StreamCompanion version: 160629.14

map 1 : https://osu.ppy.sh/s/3558
map 2 : https://osu.ppy.sh/s/477474
map 3 : https://osu.ppy.sh/s/15972
map 4 : https://osu.ppy.sh/s/454329

**How it happened and things I tried:**

I had SC opened, was in osu! song selection screen and imported a new map (map 1) to the game. SC showed the map as "notFound" followed by the name of the song. Starting to play the map SC changed to display a invalid character followed by the mods I had activated. The character looks like a rectangle standing on one of its shorter side.( If you are on windows I know you can get a similar character by opening notepad and pressing ctrl+backspace)

The map was a little to difficult so I failed and return to song selection and then SC showed the name of the map correctly, after changing mods I gave it a new attempt and SC updated to again display this invalid character followed by my current mods... after this I decided to play around a little to see what fixes this and maybe test if I can replicated it for another map.

Even with changing my mods it was still to difficult and I failed and return to song selection after a few retries, once again SC shows the title correctly in selection screen.

I tried switching focus to another map,  then back again, change my mods again and give map another go. Still displays incorrect while playing, not in song selection.

Failing and returning, picking another map and this time playing it, SC displays  the other song correctly. I lose on purpose and go back to the map that did not work and give it another try with the same mods, still does not work.

I have not tried without mods yet so I try it now, no difference. This time I finish the song and on the score screen it displays correctly like in song selection. On the score screen I press retry and the name is once again broken so I quit back to song selection.

Next I try to switch song, close SC, reopen SC, randomizing song a few times and then search up the song that did not work again and play it. now it displays as it should.

**Lets try to replicate it!**

Everything from now is no mods
Now I picked a new song (map 2) to test with, I position osu! in song selection with a empty search box, downloaded the map and double-clicked to import it. The name looked right in SC but I changed to another difficulty of map a little too quickly beacuse it looked like the name changed (not sure, may be in my head only). I started playing the song and it appeared correctly in SC.

**hmm**
**Lets try another map (map 3)**

This time I had some text in the search box that did not match any of the maps on my computer. This time it happened again "notFound"-songname
(Changing diff did not change text in Stream Companion)
playing the map gives the unknown character. This time I managed to save some screen shots! on the first map I took a screen shot but forgot to save it and got lost then I copied something else.
screen shots: http://imgur.com/a/jOeWA

**what! map 4**

something strange happened, like for map 3 I wrote some random stuff in the search box before importing the map and it displayed "notFound"-mapname  as before. But this time then I started the map the name displayed correctly... after finnishing the map the name was correct in SC.

So I thought "how is it with map 3 now?" and played it again to see if the name displays correct, it does not 

This has taken a lot of time to test and write, hopefully some parts of it is usefull

I am the only one reporting bugs or am I just doing it at the wrong place?

**Comment by ColdVolcano** [comment]
This happens because when a map is first imported in osu! it is not issued in the beatmap database, so It says "not found" for that reason, the map is issued in the database once there is a reload of it, just like when you import a song and you were grouping by difficulty and osu! groups that map as "Not Yet Calculated"
I may sugguest to try to find the song manually in the song folder when a "not found" error is thrown, that may be the thing.
And for the Invalid Character... I can't reproduce it, so I don't know why it is happening.
Tested with osu!direct.

**Comment by Stekeblad** [comment]
osu!direct is that the in-game downloader for supporters? I am not a supporter so I download maps from the website and then double click on the file to import it. osu!direct may work in a slightly different way, try with it disabled? 
I may try later getting the error again and look at the songs folder if it is of any interest.

**Comment by Piotrekol** [comment]
> I am the only one reporting bugs or am I just doing it at the wrong place?

Almost all error reports so far are sent to me using osu! (website/irc) but these hardly ever contain anything else than hard crashes. Also, I never specified where to post crash/bug reports(other than built-in "click to send me a osu! PM" button in crash window) so I'm partially at fault there.

\[\] (or "Invalid Character"?) is just **[this line](https://github.com/Piotrekol/StreamCompanion/blob/master/osu!StreamCompanion/Code/Modules/MapDataGetters/Window/WindowDataGetter.cs#L22)** not getting data is should be provided with the given  conditions 

I believe all of this is caused by [**this code**](https://github.com/Piotrekol/StreamCompanion/blob/master/osu!StreamCompanion/Code/Modules/osuSongsFolderWatcher/osuSongsFolderWatcher.cs#L41-L48) not having enough time to save new beatmap data from *.osu file(and thus, all "beatmap searchers" failing to get map data)
While that might not be an ideal solution I believe I could just make it retry specified search after some time elapsed.
I'll do some tests today/tomorrow and see what can be done.

**Comment by Piotrekol** [comment]
I tried to follow everything as you described and I wasn't able to reproduce any of this neither on SSD or quite slow external drive.
Even with that I still believe that what I wrote above can happen, so I'll still include a safety mechanism that should prevent that from happening again.
