### ISSUE TITLE
Ingame browser overlay not loading

### ISSUE THREAD

**Issue by CyberGen49** [Piotrekol/StreamCompanion#320]
Hey,

I've followed all of the instructions listed in the wiki in regards to setting up the ingame browser overlay, but to no avail. I have access to the options for it, and I'm prompted to restart my game when starting StreamCompanion, but nothing shows up ingame. I've also confirmed that my target overlay is valid (loads fine in my main browser).

I opened up the console logger to see if anything shows up, and upon starting the game, the following is logged:
```
[Deb] 12:29:21 AM [      BrowserOverlay] - This is a list of unknown files loaded in osu!. If you are experiencing startup osu! crashes or overlay just not appearing ingame, these will help with finding conflicting application:
mdnsnsp.dll
nvldumd.dll
nvd3dum.dll
nvspcap.dll
sxs.dll
[Deb] 12:29:21 AM [      BrowserOverlay] - Injecting
[Inf] 12:29:21 AM [      BrowserOverlay] - Injection success.
```

Could these .dll files have anything to do with the overlay not showing up?

If it means anything, this is a portable install of StreamCompanion.

Responses appreciated!

**Comment by Piotrekol** [comment]
overlay does work on my machine. dll analysis:
```
mdnsnsp.dll - no clue
nvldumd.dll - nvidia
nvd3dum.dll - nvidia
nvspcap.dll - nvidia, I also have this logged
sxs.dll - windows, I also have this logged
```
Are you totally sure that you have at least one overlay configured to be displayed WITHIN osu! window bounds?

**Comment by Piotrekol** [comment]
Check if installing vcredist changes anything:
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by CyberGen49** [comment]
Installed and restarted my PC, but sadly no luck.

**Comment by whatsup1827** [comment]
Overlay appears to be broken for me too. Tested on stable and cutting edge,

**Comment by cchamberlain** [comment]
This is the part where it is failing for me. I can see that it is accurately telling whether its playing or listening etc. but it thinks the mapset is not valid.
![image](https://user-images.githubusercontent.com/424694/136662897-ae1431fb-ddd8-4f34-a675-4ef24db0a6d5.png)

**Comment by cchamberlain** [comment]
> @cchamberlain unrelated, see #321

Thanks! I managed to get it working through some combination of run as administrator between osu and StreamCompanion (possibly unrelated to root cause) but one thing I noticed is it crashes often during the welcome screen. I was on cutting edge for a while but I've been on stable through all of these tests. It was running pretty good until today when it all of a sudden stopped receiving any information about whether osu is playing a song or not. Tried doing multiple restarts etc. and just reinstalled StreamCompanion and seeing the same issues originally reported here. Will try out the DLLs that you linked on the other thread and update there.

Really appreciate StreamCompanion, its amazing. I'm a C# / TypeScript eng so if there is any known work type of stuff, happy to submit PRs (time permitted).


Here is a screenshot from event viewer that happens every time osu crashes during startup (the other exception that follows is a non-descript result of this saying osu crashed). I tried giving `Everyone` access to osu file system but didn't help (think its more likely concurrent device access or something).
![image](https://user-images.githubusercontent.com/424694/137251168-fb375ce5-9276-4871-9ec4-227ffc6cfed2.png)

**Comment by CyberGen49** [comment]
I've found the fix! It's osu's compatibility mode. The overlay refuses to load with compatibility mode on, but turning it off makes everything work as it should. I found this in the documentation for [gosumemory](https://github.com/l3lackShark/gosumemory/wiki/GameOverlay), which mentioned that their browser overlay would crash the game with compatibility mode on.
