### ISSUE TITLE
Missing mapStrains values in osu!mania

### ISSUE THREAD

**Issue by iamgqr** [Piotrekol/StreamCompanion#348]
Currently `mapStrains` token of plugin `OsuMemoryEventSource` returns all zeros for osu!mania mode, but works on every other mode. If I can't make it work using settings, then this is a feature request.

**Comment by Piotrekol** [comment]
this is both a bug and a feature request. Mania performance calc - unlike other modes - depends on score achieved instead of tracking individual hit results.
What current mapStrains token represents is the performance values of small sections of the map, which would explain it being 0 for all of these since score is not filled/used anywhere except for live performance calculations.

Proper fix requires refactoring mapStrains to use actual difficulty calculation instead of performance calculation - not sure how involved these changes would be at the moment.

**Comment by Piotrekol** [comment]
Never mind, applied a temporary solution - mania strains values should now be populated.
However, while not necessary at the moment, strains eventually should be generated using difficulty calculation instead of performance calc (proper fix mentioned previously)
