### ISSUE TITLE
not loading all maps [Aspire 2018]

### ISSUE THREAD

**Issue by InvisibleSymbol** [Piotrekol/StreamCompanion#45]
![](https://i.fiery.me/qfam.png)
happens when this file is imported: https://i.fiery.me/uLI3.osz
Source of Map : https://osu.ppy.sh/home/news/2018-02-21-aspire-2018-voting-now-open
removing the map from the song folder *__and rescanning the maps in osu!__* fixes the problem

**Comment by Piotrekol** [comment]
Some info, there were 2 issues:
map you linked has (imo) invalid AudioLeadIn value of `-2147272727`. That caused OverflowException with stopped further processing when map was hot loaded from .osu file.

Second one: 
That map also contains: `StackLeniency: NaN` with I had no idea was valid value - that caused both osu!.db and SC database loads to fail because of invalid casts(null).
