### ISSUE TITLE
[Feature Request] WebSocket to create cutsom counters

### ISSUE THREAD

**Issue by uzervlad** [Piotrekol/StreamCompanion#67]
Using Websockets people can create their own counters, just like with osu!Sync (+ODDR)

**Comment by Piotrekol** [comment]
Have you seen / tried to use TCP socket output? 
Does it lack something or are you not able to use it for some reason?
https://github.com/Piotrekol/StreamCompanion/issues/19

**Comment by uzervlad** [comment]
Tried it with Node.JS, seems to work but here's the problem:
I can create an Electron app with a counter, but it would weight a LOT. Having just a small web-page counter would be much better for a typical user.

_Please correct me, if it is actually possible to connect using a single web-page_

**Comment by Piotrekol** [comment]
Smillar to TCP socket, live and map data is sent separately.
Once websocket plugin gets enabled in output patterns tab in settings, StreamCompanion creates server listening on loopback address.
In there you have access to 2 endpoints
```
/StreamCompanion/LiveData/Stream
/StreamCompanion/MapData/Stream
```
Both only send data when it actually updates, instead of spamming clients with constant spam of redundant data.
![image](https://user-images.githubusercontent.com/4990365/59567819-15a0a880-9073-11e9-9534-ab3c6c6d4176.png)
![image](https://user-images.githubusercontent.com/4990365/59567842-56002680-9073-11e9-8140-06c89fe8c039.png)

**Comment by uzervlad** [comment]
Thanks, works good, but after some time it just closes the connection
![image](https://user-images.githubusercontent.com/24654479/59601269-35d07600-910c-11e9-9eca-66c308dd5044.png)

**Comment by Piotrekol** [comment]
Is this still an issue? anything specific in order to reproduce disconnection behavior?

**Comment by uzervlad** [comment]
Yes, the problem it still there. Nothing specific, it will disconnect in any case in a few minutes

**Comment by Piotrekol** [comment]
As a client it's your responsibility for keeping connection alive(notifying server that you're still there). 
All you need to do is to add code needed to send _anything_ to server every 50-60seconds or so.

After adding `setInterval(()=>ws.send("ping"),50000);` to my test page, connection stopped dropping(tested for ~15mins).
