### ISSUE TITLE
Improvement for PP calc when mapping?

### ISSUE THREAD

**Issue by Fleepy** [Piotrekol/StreamCompanion#80]
One thing ive been wanting to ask, and or if its a bug, Is if SC could calculate PP once it detected the currently loaded beatmap was edited or saved. Just a thought.

**Comment by Piotrekol** [comment]
Not a bug. It just doesn't monitor existing files at the moment(but pp calculator loads them each time).
This can be done in 2 ways:
1. (lazy/easy/dirty) Add FileWatcher to all ppCalculator instances - but it'll only reflect changes on ppCalculator itself, so AR/CS/map length etc won't get updated with seems broken.

2. (obviously harder but more correct) Modify `OsuSongsFolderWatcher` so it also watches for file changes instead of just creation, and re-fires last `MapSearchArgs` to the rest application(new interface/handling for that is necessary).
